name: Setup Steam Secrets

on: workflow_dispatch

jobs:
  steam:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup steamcmd
        uses: CyberAndrii/setup-steamcmd@v1.1.1
      - name: Run steamcmd
        run: steamcmd +login ${{ secrets.STEAM_USERNAME }} ${{ secrets.STEAM_PASSWORD }} ${{secrets.STEAM_MFA_CODE }} +quit
      - name: Export secret values
        id: secreting
        run: |
          echo "Exporting STEAM_CONFIG_VDF..."
          export STEAM_CONFIG_VDF="$(cat /home/runner/Steam/config/config.vdf | base64)"
          echo "::set-output name=STEAM_CONFIG_VDF::$STEAM_CONFIG_VDF"
          echo "Exporting STEAM_SSFN_FILE_NAME..."
          export STEAM_SSFN_FILE_NAME="$(ls /home/runner/Steam/ssfn*)"
          echo "::set-output name=STEAM_SSFN_FILE_NAME::$STEAM_SSFN_FILE_NAME"
          echo "Exporting STEAM_SSFN_FILE_CONTENTS..."
          export STEAM_SSFN_FILE_CONTENTS="$(cat /home/runner/Steam/$STEAM_SSFN_FILE_NAME | base64)"
          echo "::set-output name=STEAM_SSFN_FILE_CONTENTS::$STEAM_SSFN_FILE_CONTENTS"
          echo "Exported secrets!"
      - name: Create Secret STEAM_CONFIG_VDF
        uses: gliech/create-github-secret-action@v1
        with:
          name: STEAM_CONFIG_VDF
          value: ${{ steps.secreting.outputs.STEAM_CONFIG_VDF }}
          pa_token: ${{ secrets.CGS_PAT }}
      - name: Create Secret STEAM_SSFN_FILE_NAME
        uses: gliech/create-github-secret-action@v1
        with:
          name: STEAM_SSFN_FILE_NAME
          value: ${{ steps.secreting.outputs.STEAM_SSFN_FILE_NAME }}
          pa_token: ${{ secrets.CGS_PAT }}
      - name: Create Secret STEAM_SSFN_FILE_CONTENTS
        uses: gliech/create-github-secret-action@v1
        with:
          name: STEAM_SSFN_FILE_CONTENTS
          value: ${{ steps.secreting.outputs.STEAM_SSFN_FILE_CONTENTS }}
          pa_token: ${{ secrets.CGS_PAT }}
